version: "3"

services:
  app:
    build:
      context: app
    ports:
      - "5000"
    depends_on:
      - mongo
      - redis
    environment:
      - REDIS_HOST=redis
      - MONGO_HOST=mongodb://mongo

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "8080:8080"

  mongo:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    ports:
    - "6379:6379"
